site_name: 'Techdocs test'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/victormorfin97/techdocs-test

plugins:
  - techdocs-core

nav:
  - Home: index.md
  - Other File: secondFile.md
